import { describe, expect, it } from 'vitest'
import { buildUnderwritingSection } from './underwritingPages'
import type { DealUnderwriting } from '#/data/types'

const READY = (over: Partial<DealUnderwriting>): DealUnderwriting => ({
  strategy: 'new-construction',
  tier: 'New Construction Strategy',
  selectedChecks: [0, 1, 2, 3, 4, 5, 6],
  status: 'ready',
  ...over,
})

describe('buildUnderwritingSection', () => {
  it('returns nothing until the underwriting is ready', () => {
    expect(buildUnderwritingSection(undefined, READY({ status: 'generating' }))).toEqual([])
    expect(buildUnderwritingSection(undefined, undefined)).toEqual([])
  })

  it('builds a summary page plus content pages for the selected new-construction checks', () => {
    const pages = buildUnderwritingSection(undefined, READY({}))
    expect(pages[0].name).toBe('Underwriting')
    // Summary subtitle carries the strategy label.
    const subtitle = pages[0].blocks.find(
      (b) => b.type === 'text' && String((b as { text?: string }).text).includes('Generated by Cactus'),
    ) as { text: string }
    expect(subtitle.text).toContain('New Construction Strategy')
    // 7 checks → summary + ceil(7/2) content pages = 1 + 4.
    expect(pages).toHaveLength(5)
  })

  it('builds value-add sections when that strategy is chosen', () => {
    const pages = buildUnderwritingSection(
      undefined,
      READY({ strategy: 'value-add', tier: 'Value-Add Strategy', selectedChecks: [1, 3] }),
    )
    const names = pages.map((p) => p.name).join(' | ')
    expect(names).toContain('Current Rent Roll')
    expect(names).toContain('Renovation')
  })

  it('falls back to the default strategy when the record has none (legacy)', () => {
    const legacy = { tier: 'x', selectedChecks: [0], status: 'ready' } as unknown as DealUnderwriting
    const pages = buildUnderwritingSection(undefined, legacy)
    expect(pages.length).toBeGreaterThan(1)
  })
})
