import { Avatar } from "@buildoutinc/blueprint-react/ui/Avatar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faAlarmExclamation,
  faCheck,
  faHandshake,
  faSparkles,
  faUser,
} from "@fortawesome/pro-regular-svg-icons";
import type { TaskView } from "#/data/types";
import { shouldIgnoreRowClick } from "#/components/contacts/rowClick";
import { todayISO } from "#/components/contacts/contactDisplay";
import {
  TASK_TYPE_LABELS,
  taskDueLabel,
  type TaskTypeKey,
} from "#/components/contacts/taskDisplay";

/**
 * A task row on the Tasks page — the same inset "card" tile as the contact
 * detail column, but always showing the assignee (name + photo) and a source
 * badge for the deal or contact the task hangs off. Clicking opens the task;
 * the checkbox toggles completion. Reuses the `.contact-task-card` styles.
 */
export function TaskListRow({
  task,
  onToggle,
  onOpen,
}: {
  task: TaskView;
  onToggle: () => void;
  onOpen: () => void;
}) {
  const due = taskDueLabel(task.dueDate);
  const isOverdue = !task.completed && !!task.dueDate && task.dueDate < todayISO();
  const typeLabel = task.type
    ? TASK_TYPE_LABELS[task.type as TaskTypeKey]
    : null;

  return (
    <div
      className={`contact-task-card contact-task-card--interactive${
        task.completed ? " contact-task-card--done" : ""
      }`}
      role="button"
      onClick={(e) => {
        if (!shouldIgnoreRowClick(e)) onOpen();
      }}
    >
      <div className="contact-task-card__inner">
        <button
          type="button"
          role="checkbox"
          aria-checked={task.completed}
          aria-label={task.completed ? "Mark task incomplete" : "Mark task complete"}
          className="contact-task-card__check"
          onClick={onToggle}
        >
          {task.completed && <FontAwesomeIcon icon={faCheck} />}
        </button>

        <div className="contact-task-card__content">
          {/* Top row: title + assignee (name + avatar) */}
          <div className="contact-task-card__titlerow">
            <span className="contact-task-card__label">{task.title}</span>
            <span className="contact-task-card__assignee">
              <span className="contact-task-card__assignee-name">
                {task.assigneeName}
              </span>
              <Avatar
                size="sm"
                className="contact-task-card__avatar"
                style={{ width: 18, height: 18 }}
              >
                {task.assigneeAvatarUrl && (
                  <Avatar.Image
                    src={task.assigneeAvatarUrl}
                    alt={task.assigneeName}
                  />
                )}
                <Avatar.Fallback style={{ fontSize: 8 }}>
                  {task.assigneeInitials}
                </Avatar.Fallback>
              </Avatar>
            </span>
          </div>

          {/* Bottom row: badges + due date */}
          <div className="contact-task-card__meta">
            <div className="contact-task-card__badges">
              {task.autoGenerated && (
                <span
                  className="contact-task-card__badge contact-task-card__badge--ai"
                  aria-label="AI suggested"
                  title="AI suggested"
                >
                  <FontAwesomeIcon icon={faSparkles} />
                </span>
              )}
              {typeLabel && (
                <span className="contact-task-card__badge contact-task-card__badge--type">
                  {typeLabel}
                </span>
              )}
              {task.sourceKind !== "none" && (
                <span
                  className="contact-task-card__badge contact-task-card__badge--deal"
                  title={task.sourceLabel}
                >
                  <FontAwesomeIcon
                    icon={task.sourceKind === "deal" ? faHandshake : faUser}
                  />
                  <span className="text-truncate">{task.sourceLabel}</span>
                </span>
              )}
            </div>

            {due && (
              <span
                className={`contact-task-card__due${
                  isOverdue ? " contact-task-card__due--overdue" : ""
                }`}
              >
                {isOverdue && <FontAwesomeIcon icon={faAlarmExclamation} />}
                {due}
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
