import { useState } from "react";
import { Button } from "@buildoutinc/blueprint-react/ui/Button";
import { Avatar } from "@buildoutinc/blueprint-react/ui/Avatar";
import { Progress } from "@buildoutinc/blueprint-react/ui/Progress";
import { Empty } from "@buildoutinc/blueprint-react/ui/Empty";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPlus,
  faCheck,
  faCalendar,
  faPhone,
  faEnvelope,
  faNoteSticky,
  faClockRotateLeft,
} from "@fortawesome/pro-regular-svg-icons";
import type { Listing, DealTask } from "#/data/types";
import { STATUS_COLORS } from "#/components/properties/propertyDisplay";
import { ListingPageHeader } from "../listings/ListingPageHeader";

const ACCENT = STATUS_COLORS.proposal;
/** Opaque accent tint so markers sit cleanly on top of the timeline spine. */
const ACCENT_TILE = `color-mix(in srgb, ${ACCENT} 12%, var(--bs-card-bg, #fff))`;
const SURFACE = "var(--bs-card-bg, #fff)";
const SPINE = "#e2e8f0";

/** "3 AUG, 2026" — the compact planner date style. */
function formatPlannerDate(iso: string | null): string {
  if (!iso) return "TBD";
  const d = new Date(iso);
  const mon = d.toLocaleDateString("en-US", { month: "short" }).toUpperCase();
  return `${d.getDate()} ${mon}, ${d.getFullYear()}`;
}

/** Borderless section with a rail-style h6 heading (+ optional action). */
function Section({
  title,
  action,
  children,
}: {
  title: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="d-flex align-items-center justify-content-between gap-2 mb-3">
        <h6 className="mb-0">{title}</h6>
        {action}
      </div>
      {children}
    </section>
  );
}

type SpinePosition = "start" | "middle" | "end";

/** A row on the planner timeline: a marker in the gutter, connected by the spine. */
function PlannerRow({
  marker,
  spine,
  right,
  children,
}: {
  marker: React.ReactNode;
  spine: SpinePosition;
  right?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="position-relative d-flex align-items-center gap-3 py-3">
      <span
        aria-hidden
        style={{
          position: "absolute",
          left: 15,
          width: 2,
          background: SPINE,
          top: spine === "start" ? "50%" : 0,
          bottom: spine === "end" ? "50%" : 0,
        }}
      />
      <span
        className="flex-shrink-0 d-flex justify-content-center"
        style={{ width: 32, position: "relative" }}
      >
        {marker}
      </span>
      <div className="flex-grow-1" style={{ minWidth: 0 }}>
        {children}
      </div>
      {right}
    </div>
  );
}

function MilestoneMarker() {
  return (
    <span
      className="d-inline-flex align-items-center justify-content-center rounded"
      style={{ width: 32, height: 32, backgroundColor: ACCENT_TILE, color: ACCENT }}
    >
      <FontAwesomeIcon icon={faCalendar} />
    </span>
  );
}

function TaskMarker({
  complete,
  onToggle,
}: {
  complete: boolean;
  onToggle: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-label={complete ? "Mark task incomplete" : "Mark task complete"}
      className="btn btn-link p-0 border-0"
      style={{ lineHeight: 0 }}
    >
      <span
        className="d-inline-flex align-items-center justify-content-center rounded-circle"
        style={{
          width: 22,
          height: 22,
          border: complete ? "none" : "2px solid #cbd5e1",
          backgroundColor: complete ? "#16a34a" : SURFACE,
          color: "#fff",
          fontSize: 11,
        }}
      >
        {complete && <FontAwesomeIcon icon={faCheck} />}
      </span>
    </button>
  );
}

function Milestone({
  label,
  date,
  spine,
}: {
  label: string;
  date: string | null;
  spine: SpinePosition;
}) {
  return (
    <PlannerRow marker={<MilestoneMarker />} spine={spine}>
      <div className="fw-semibold">{label}</div>
      <div className="fw-semibold" style={{ fontSize: 13, color: ACCENT }}>
        {formatPlannerDate(date)}
      </div>
    </PlannerRow>
  );
}

function TaskRow({ task, onToggle }: { task: DealTask; onToggle: () => void }) {
  const complete = task.status === "complete";
  const showReview = task.autoGenerated && complete;

  return (
    <PlannerRow
      spine="middle"
      marker={<TaskMarker complete={complete} onToggle={onToggle} />}
      right={
        showReview ? (
          <Button variant="outline" size="sm" className="flex-shrink-0">
            Review
          </Button>
        ) : (
          <Avatar size="sm" className="flex-shrink-0">
            <Avatar.Fallback>{task.assigneeInitials}</Avatar.Fallback>
          </Avatar>
        )
      }
    >
      <div className="fw-semibold">{task.label}</div>
      {task.detail && (
        <div className="text-muted" style={{ fontSize: 13 }}>
          {task.detail}
        </div>
      )}
      {!complete && task.date && (
        <div className="text-muted" style={{ fontSize: 13 }}>
          {formatPlannerDate(task.date)}
          {task.relativeDue ? ` · ${task.relativeDue}` : ""}
        </div>
      )}
    </PlannerRow>
  );
}

function Planner({ listing }: { listing: Listing }) {
  const [tasks, setTasks] = useState<DealTask[]>(listing.tasks);

  const done = tasks.filter((t) => t.status === "complete").length;
  const total = tasks.length;
  const pct = total > 0 ? Math.round((done / total) * 100) : 0;

  const toggle = (id: string) =>
    setTasks((prev) =>
      prev.map((t) =>
        t.id === id
          ? { ...t, status: t.status === "complete" ? "open" : "complete" }
          : t,
      ),
    );

  const expires = new Date(listing.createdAt);
  expires.setDate(expires.getDate() + 180);

  return (
    <Section
      title="Planner"
      action={
        <div className="d-flex align-items-center gap-1">
          <Button variant="ghost" size="sm">
            <FontAwesomeIcon icon={faPlus} />
            Add task
          </Button>
          <Button variant="ghost" size="sm">
            <FontAwesomeIcon icon={faPlus} />
            Add critical date
          </Button>
        </div>
      }
    >
      <div className="d-flex align-items-center justify-content-between mb-2">
        <span className="fw-semibold">
          {done} of {total} tasks done
        </span>
        <span className="fw-semibold" style={{ color: ACCENT }}>
          {pct}%
        </span>
      </div>
      <Progress value={pct} />

      <div className="mt-3">
        <Milestone label="Listing executed" date={listing.createdAt} spine="start" />
        {tasks.map((t) => (
          <TaskRow key={t.id} task={t} onToggle={() => toggle(t.id)} />
        ))}
        <Milestone
          label="Listing expires"
          date={expires.toISOString()}
          spine="end"
        />
      </div>
    </Section>
  );
}

function Activity() {
  return (
    <Section title="Activity Timeline">
      <div className="d-flex gap-2 mb-3">
        <Button variant="outline" size="sm">
          <FontAwesomeIcon icon={faPhone} />
          Log call
        </Button>
        <Button variant="outline" size="sm">
          <FontAwesomeIcon icon={faEnvelope} />
          Log email
        </Button>
        <Button variant="outline" size="sm">
          <FontAwesomeIcon icon={faNoteSticky} />
          Add note
        </Button>
      </div>
      <Empty className="py-4">
        <Empty.Media>
          <FontAwesomeIcon icon={faClockRotateLeft} aria-hidden />
        </Empty.Media>
        <Empty.Content>
          <Empty.Title>No activity logged yet</Empty.Title>
          Log a call, email, or note above.
        </Empty.Content>
      </Empty>
    </Section>
  );
}

/**
 * Action-oriented overview for a freshly created proposal: an auto-generated
 * planner (with a live progress bar and timeline) plus an activity timeline —
 * everything the broker needs to start moving the deal forward. Files and deal
 * facts live in the persistent right rail; sections here are separated by
 * whitespace rather than card borders, since the page already sits inside the
 * detail card.
 */
export function ProposalOverview({ listing }: { listing: Listing }) {
  return (
    <div className="d-flex flex-column gap-5 p-4">
      <ListingPageHeader
        title="Overview"
        actions={<Button variant="primary">Publish listing</Button>}
      />
      <Planner listing={listing} />
      <Activity />
    </div>
  );
}
