/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiteRouteImport } from './routes/suite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiteIndexRouteImport } from './routes/suite/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ListingsListingIdRouteImport } from './routes/listings/$listingId'
import { Route as ListingsListingIdIndexRouteImport } from './routes/listings/$listingId/index'
import { Route as ListingsListingIdLeadsRouteImport } from './routes/listings/$listingId/leads'

const SuiteRoute = SuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiteIndexRoute = SuiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuiteRoute,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => ListingsRoute,
} as any)
const ListingsListingIdIndexRoute = ListingsListingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdLeadsRoute = ListingsListingIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ListingsListingIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/suite': typeof SuiteRouteWithChildren
  '/listings/$listingId': typeof ListingsListingIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/suite/': typeof SuiteIndexRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/suite': typeof SuiteIndexRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId': typeof ListingsListingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/suite': typeof SuiteRouteWithChildren
  '/listings/$listingId': typeof ListingsListingIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/suite/': typeof SuiteIndexRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/listings'
    | '/login'
    | '/suite'
    | '/listings/$listingId'
    | '/app/'
    | '/listings/'
    | '/suite/'
    | '/listings/$listingId/leads'
    | '/listings/$listingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/listings'
    | '/suite'
    | '/listings/$listingId/leads'
    | '/listings/$listingId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/listings'
    | '/login'
    | '/suite'
    | '/listings/$listingId'
    | '/app/'
    | '/listings/'
    | '/suite/'
    | '/listings/$listingId/leads'
    | '/listings/$listingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuiteRoute: typeof SuiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suite': {
      id: '/suite'
      path: '/suite'
      fullPath: '/suite'
      preLoaderRoute: typeof SuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suite/': {
      id: '/suite/'
      path: '/'
      fullPath: '/suite/'
      preLoaderRoute: typeof SuiteIndexRouteImport
      parentRoute: typeof SuiteRoute
    }
    '/listings/': {
      id: '/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/listings/$listingId/': {
      id: '/listings/$listingId/'
      path: '/'
      fullPath: '/listings/$listingId/'
      preLoaderRoute: typeof ListingsListingIdIndexRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/leads': {
      id: '/listings/$listingId/leads'
      path: '/leads'
      fullPath: '/listings/$listingId/leads'
      preLoaderRoute: typeof ListingsListingIdLeadsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ListingsListingIdRouteChildren {
  ListingsListingIdLeadsRoute: typeof ListingsListingIdLeadsRoute
  ListingsListingIdIndexRoute: typeof ListingsListingIdIndexRoute
}

const ListingsListingIdRouteChildren: ListingsListingIdRouteChildren = {
  ListingsListingIdLeadsRoute: ListingsListingIdLeadsRoute,
  ListingsListingIdIndexRoute: ListingsListingIdIndexRoute,
}

const ListingsListingIdRouteWithChildren =
  ListingsListingIdRoute._addFileChildren(ListingsListingIdRouteChildren)

interface ListingsRouteChildren {
  ListingsListingIdRoute: typeof ListingsListingIdRouteWithChildren
  ListingsIndexRoute: typeof ListingsIndexRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsListingIdRoute: ListingsListingIdRouteWithChildren,
  ListingsIndexRoute: ListingsIndexRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface SuiteRouteChildren {
  SuiteIndexRoute: typeof SuiteIndexRoute
}

const SuiteRouteChildren: SuiteRouteChildren = {
  SuiteIndexRoute: SuiteIndexRoute,
}

const SuiteRouteWithChildren = SuiteRoute._addFileChildren(SuiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  SuiteRoute: SuiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
