/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiteRouteImport } from './routes/suite'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiteIndexRouteImport } from './routes/suite/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as EmailIndexRouteImport } from './routes/email/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties/$propertyId'
import { Route as ListingsListingIdRouteImport } from './routes/listings/$listingId'
import { Route as EmailEmailIdRouteImport } from './routes/email/$emailId'
import { Route as EditorListingIdRouteImport } from './routes/editor/$listingId'
import { Route as ListingsListingIdIndexRouteImport } from './routes/listings/$listingId/index'
import { Route as BackofficeContactsIndexRouteImport } from './routes/backoffice/contacts/index'
import { Route as ListingsListingIdWebsiteRouteImport } from './routes/listings/$listingId/website'
import { Route as ListingsListingIdTransactionRouteImport } from './routes/listings/$listingId/transaction'
import { Route as ListingsListingIdOverviewRouteImport } from './routes/listings/$listingId/overview'
import { Route as ListingsListingIdMediaRouteImport } from './routes/listings/$listingId/media'
import { Route as ListingsListingIdLeadsRouteImport } from './routes/listings/$listingId/leads'
import { Route as ListingsListingIdGridsRouteImport } from './routes/listings/$listingId/grids'
import { Route as ListingsListingIdFinancialsRouteImport } from './routes/listings/$listingId/financials'
import { Route as ListingsListingIdFilesRouteImport } from './routes/listings/$listingId/files'
import { Route as ListingsListingIdEmailRouteImport } from './routes/listings/$listingId/email'
import { Route as ListingsListingIdEditRouteImport } from './routes/listings/$listingId/edit'
import { Route as ListingsListingIdDocumentsRouteImport } from './routes/listings/$listingId/documents'
import { Route as ListingsListingIdDemographicsRouteImport } from './routes/listings/$listingId/demographics'
import { Route as ListingsListingIdClientReportRouteImport } from './routes/listings/$listingId/client-report'
import { Route as ListingsListingIdActivitiesRouteImport } from './routes/listings/$listingId/activities'
import { Route as BackofficeContactsContactIdRouteImport } from './routes/backoffice/contacts/$contactId'

const SuiteRoute = SuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiteIndexRoute = SuiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuiteRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsRoute,
} as any)
const EmailIndexRoute = EmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropertiesRoute,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => ListingsRoute,
} as any)
const EmailEmailIdRoute = EmailEmailIdRouteImport.update({
  id: '/$emailId',
  path: '/$emailId',
  getParentRoute: () => EmailRoute,
} as any)
const EditorListingIdRoute = EditorListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => EditorRoute,
} as any)
const ListingsListingIdIndexRoute = ListingsListingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const BackofficeContactsIndexRoute = BackofficeContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => BackofficeRoute,
} as any)
const ListingsListingIdWebsiteRoute =
  ListingsListingIdWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdTransactionRoute =
  ListingsListingIdTransactionRouteImport.update({
    id: '/transaction',
    path: '/transaction',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdOverviewRoute =
  ListingsListingIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdMediaRoute = ListingsListingIdMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdLeadsRoute = ListingsListingIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdGridsRoute = ListingsListingIdGridsRouteImport.update({
  id: '/grids',
  path: '/grids',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdFinancialsRoute =
  ListingsListingIdFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdFilesRoute = ListingsListingIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdEmailRoute = ListingsListingIdEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdEditRoute = ListingsListingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ListingsListingIdRoute,
} as any)
const ListingsListingIdDocumentsRoute =
  ListingsListingIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdDemographicsRoute =
  ListingsListingIdDemographicsRouteImport.update({
    id: '/demographics',
    path: '/demographics',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdClientReportRoute =
  ListingsListingIdClientReportRouteImport.update({
    id: '/client-report',
    path: '/client-report',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const ListingsListingIdActivitiesRoute =
  ListingsListingIdActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => ListingsListingIdRoute,
  } as any)
const BackofficeContactsContactIdRoute =
  BackofficeContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => BackofficeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/editor': typeof EditorRouteWithChildren
  '/email': typeof EmailRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/suite': typeof SuiteRouteWithChildren
  '/editor/$listingId': typeof EditorListingIdRoute
  '/email/$emailId': typeof EmailEmailIdRoute
  '/listings/$listingId': typeof ListingsListingIdRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/app/': typeof AppIndexRoute
  '/email/': typeof EmailIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/suite/': typeof SuiteIndexRoute
  '/backoffice/contacts/$contactId': typeof BackofficeContactsContactIdRoute
  '/listings/$listingId/activities': typeof ListingsListingIdActivitiesRoute
  '/listings/$listingId/client-report': typeof ListingsListingIdClientReportRoute
  '/listings/$listingId/demographics': typeof ListingsListingIdDemographicsRoute
  '/listings/$listingId/documents': typeof ListingsListingIdDocumentsRoute
  '/listings/$listingId/edit': typeof ListingsListingIdEditRoute
  '/listings/$listingId/email': typeof ListingsListingIdEmailRoute
  '/listings/$listingId/files': typeof ListingsListingIdFilesRoute
  '/listings/$listingId/financials': typeof ListingsListingIdFinancialsRoute
  '/listings/$listingId/grids': typeof ListingsListingIdGridsRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId/media': typeof ListingsListingIdMediaRoute
  '/listings/$listingId/overview': typeof ListingsListingIdOverviewRoute
  '/listings/$listingId/transaction': typeof ListingsListingIdTransactionRoute
  '/listings/$listingId/website': typeof ListingsListingIdWebsiteRoute
  '/backoffice/contacts/': typeof BackofficeContactsIndexRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/editor': typeof EditorRouteWithChildren
  '/login': typeof LoginRoute
  '/editor/$listingId': typeof EditorListingIdRoute
  '/email/$emailId': typeof EmailEmailIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/app': typeof AppIndexRoute
  '/email': typeof EmailIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/suite': typeof SuiteIndexRoute
  '/backoffice/contacts/$contactId': typeof BackofficeContactsContactIdRoute
  '/listings/$listingId/activities': typeof ListingsListingIdActivitiesRoute
  '/listings/$listingId/client-report': typeof ListingsListingIdClientReportRoute
  '/listings/$listingId/demographics': typeof ListingsListingIdDemographicsRoute
  '/listings/$listingId/documents': typeof ListingsListingIdDocumentsRoute
  '/listings/$listingId/edit': typeof ListingsListingIdEditRoute
  '/listings/$listingId/email': typeof ListingsListingIdEmailRoute
  '/listings/$listingId/files': typeof ListingsListingIdFilesRoute
  '/listings/$listingId/financials': typeof ListingsListingIdFinancialsRoute
  '/listings/$listingId/grids': typeof ListingsListingIdGridsRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId/media': typeof ListingsListingIdMediaRoute
  '/listings/$listingId/overview': typeof ListingsListingIdOverviewRoute
  '/listings/$listingId/transaction': typeof ListingsListingIdTransactionRoute
  '/listings/$listingId/website': typeof ListingsListingIdWebsiteRoute
  '/backoffice/contacts': typeof BackofficeContactsIndexRoute
  '/listings/$listingId': typeof ListingsListingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/backoffice': typeof BackofficeRouteWithChildren
  '/editor': typeof EditorRouteWithChildren
  '/email': typeof EmailRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/suite': typeof SuiteRouteWithChildren
  '/editor/$listingId': typeof EditorListingIdRoute
  '/email/$emailId': typeof EmailEmailIdRoute
  '/listings/$listingId': typeof ListingsListingIdRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/app/': typeof AppIndexRoute
  '/email/': typeof EmailIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/suite/': typeof SuiteIndexRoute
  '/backoffice/contacts/$contactId': typeof BackofficeContactsContactIdRoute
  '/listings/$listingId/activities': typeof ListingsListingIdActivitiesRoute
  '/listings/$listingId/client-report': typeof ListingsListingIdClientReportRoute
  '/listings/$listingId/demographics': typeof ListingsListingIdDemographicsRoute
  '/listings/$listingId/documents': typeof ListingsListingIdDocumentsRoute
  '/listings/$listingId/edit': typeof ListingsListingIdEditRoute
  '/listings/$listingId/email': typeof ListingsListingIdEmailRoute
  '/listings/$listingId/files': typeof ListingsListingIdFilesRoute
  '/listings/$listingId/financials': typeof ListingsListingIdFinancialsRoute
  '/listings/$listingId/grids': typeof ListingsListingIdGridsRoute
  '/listings/$listingId/leads': typeof ListingsListingIdLeadsRoute
  '/listings/$listingId/media': typeof ListingsListingIdMediaRoute
  '/listings/$listingId/overview': typeof ListingsListingIdOverviewRoute
  '/listings/$listingId/transaction': typeof ListingsListingIdTransactionRoute
  '/listings/$listingId/website': typeof ListingsListingIdWebsiteRoute
  '/backoffice/contacts/': typeof BackofficeContactsIndexRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/backoffice'
    | '/editor'
    | '/email'
    | '/listings'
    | '/login'
    | '/properties'
    | '/suite'
    | '/editor/$listingId'
    | '/email/$emailId'
    | '/listings/$listingId'
    | '/properties/$propertyId'
    | '/app/'
    | '/email/'
    | '/listings/'
    | '/properties/'
    | '/suite/'
    | '/backoffice/contacts/$contactId'
    | '/listings/$listingId/activities'
    | '/listings/$listingId/client-report'
    | '/listings/$listingId/demographics'
    | '/listings/$listingId/documents'
    | '/listings/$listingId/edit'
    | '/listings/$listingId/email'
    | '/listings/$listingId/files'
    | '/listings/$listingId/financials'
    | '/listings/$listingId/grids'
    | '/listings/$listingId/leads'
    | '/listings/$listingId/media'
    | '/listings/$listingId/overview'
    | '/listings/$listingId/transaction'
    | '/listings/$listingId/website'
    | '/backoffice/contacts/'
    | '/listings/$listingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/editor'
    | '/login'
    | '/editor/$listingId'
    | '/email/$emailId'
    | '/properties/$propertyId'
    | '/app'
    | '/email'
    | '/listings'
    | '/properties'
    | '/suite'
    | '/backoffice/contacts/$contactId'
    | '/listings/$listingId/activities'
    | '/listings/$listingId/client-report'
    | '/listings/$listingId/demographics'
    | '/listings/$listingId/documents'
    | '/listings/$listingId/edit'
    | '/listings/$listingId/email'
    | '/listings/$listingId/files'
    | '/listings/$listingId/financials'
    | '/listings/$listingId/grids'
    | '/listings/$listingId/leads'
    | '/listings/$listingId/media'
    | '/listings/$listingId/overview'
    | '/listings/$listingId/transaction'
    | '/listings/$listingId/website'
    | '/backoffice/contacts'
    | '/listings/$listingId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/backoffice'
    | '/editor'
    | '/email'
    | '/listings'
    | '/login'
    | '/properties'
    | '/suite'
    | '/editor/$listingId'
    | '/email/$emailId'
    | '/listings/$listingId'
    | '/properties/$propertyId'
    | '/app/'
    | '/email/'
    | '/listings/'
    | '/properties/'
    | '/suite/'
    | '/backoffice/contacts/$contactId'
    | '/listings/$listingId/activities'
    | '/listings/$listingId/client-report'
    | '/listings/$listingId/demographics'
    | '/listings/$listingId/documents'
    | '/listings/$listingId/edit'
    | '/listings/$listingId/email'
    | '/listings/$listingId/files'
    | '/listings/$listingId/financials'
    | '/listings/$listingId/grids'
    | '/listings/$listingId/leads'
    | '/listings/$listingId/media'
    | '/listings/$listingId/overview'
    | '/listings/$listingId/transaction'
    | '/listings/$listingId/website'
    | '/backoffice/contacts/'
    | '/listings/$listingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BackofficeRoute: typeof BackofficeRouteWithChildren
  EditorRoute: typeof EditorRouteWithChildren
  EmailRoute: typeof EmailRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SuiteRoute: typeof SuiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suite': {
      id: '/suite'
      path: '/suite'
      fullPath: '/suite'
      preLoaderRoute: typeof SuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suite/': {
      id: '/suite/'
      path: '/'
      fullPath: '/suite/'
      preLoaderRoute: typeof SuiteIndexRouteImport
      parentRoute: typeof SuiteRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/listings/': {
      id: '/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/email/': {
      id: '/email/'
      path: '/'
      fullPath: '/email/'
      preLoaderRoute: typeof EmailIndexRouteImport
      parentRoute: typeof EmailRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/email/$emailId': {
      id: '/email/$emailId'
      path: '/$emailId'
      fullPath: '/email/$emailId'
      preLoaderRoute: typeof EmailEmailIdRouteImport
      parentRoute: typeof EmailRoute
    }
    '/editor/$listingId': {
      id: '/editor/$listingId'
      path: '/$listingId'
      fullPath: '/editor/$listingId'
      preLoaderRoute: typeof EditorListingIdRouteImport
      parentRoute: typeof EditorRoute
    }
    '/listings/$listingId/': {
      id: '/listings/$listingId/'
      path: '/'
      fullPath: '/listings/$listingId/'
      preLoaderRoute: typeof ListingsListingIdIndexRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/backoffice/contacts/': {
      id: '/backoffice/contacts/'
      path: '/contacts'
      fullPath: '/backoffice/contacts/'
      preLoaderRoute: typeof BackofficeContactsIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/listings/$listingId/website': {
      id: '/listings/$listingId/website'
      path: '/website'
      fullPath: '/listings/$listingId/website'
      preLoaderRoute: typeof ListingsListingIdWebsiteRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/transaction': {
      id: '/listings/$listingId/transaction'
      path: '/transaction'
      fullPath: '/listings/$listingId/transaction'
      preLoaderRoute: typeof ListingsListingIdTransactionRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/overview': {
      id: '/listings/$listingId/overview'
      path: '/overview'
      fullPath: '/listings/$listingId/overview'
      preLoaderRoute: typeof ListingsListingIdOverviewRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/media': {
      id: '/listings/$listingId/media'
      path: '/media'
      fullPath: '/listings/$listingId/media'
      preLoaderRoute: typeof ListingsListingIdMediaRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/leads': {
      id: '/listings/$listingId/leads'
      path: '/leads'
      fullPath: '/listings/$listingId/leads'
      preLoaderRoute: typeof ListingsListingIdLeadsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/grids': {
      id: '/listings/$listingId/grids'
      path: '/grids'
      fullPath: '/listings/$listingId/grids'
      preLoaderRoute: typeof ListingsListingIdGridsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/financials': {
      id: '/listings/$listingId/financials'
      path: '/financials'
      fullPath: '/listings/$listingId/financials'
      preLoaderRoute: typeof ListingsListingIdFinancialsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/files': {
      id: '/listings/$listingId/files'
      path: '/files'
      fullPath: '/listings/$listingId/files'
      preLoaderRoute: typeof ListingsListingIdFilesRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/email': {
      id: '/listings/$listingId/email'
      path: '/email'
      fullPath: '/listings/$listingId/email'
      preLoaderRoute: typeof ListingsListingIdEmailRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/edit': {
      id: '/listings/$listingId/edit'
      path: '/edit'
      fullPath: '/listings/$listingId/edit'
      preLoaderRoute: typeof ListingsListingIdEditRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/documents': {
      id: '/listings/$listingId/documents'
      path: '/documents'
      fullPath: '/listings/$listingId/documents'
      preLoaderRoute: typeof ListingsListingIdDocumentsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/demographics': {
      id: '/listings/$listingId/demographics'
      path: '/demographics'
      fullPath: '/listings/$listingId/demographics'
      preLoaderRoute: typeof ListingsListingIdDemographicsRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/client-report': {
      id: '/listings/$listingId/client-report'
      path: '/client-report'
      fullPath: '/listings/$listingId/client-report'
      preLoaderRoute: typeof ListingsListingIdClientReportRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/listings/$listingId/activities': {
      id: '/listings/$listingId/activities'
      path: '/activities'
      fullPath: '/listings/$listingId/activities'
      preLoaderRoute: typeof ListingsListingIdActivitiesRouteImport
      parentRoute: typeof ListingsListingIdRoute
    }
    '/backoffice/contacts/$contactId': {
      id: '/backoffice/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/backoffice/contacts/$contactId'
      preLoaderRoute: typeof BackofficeContactsContactIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BackofficeRouteChildren {
  BackofficeContactsContactIdRoute: typeof BackofficeContactsContactIdRoute
  BackofficeContactsIndexRoute: typeof BackofficeContactsIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeContactsContactIdRoute: BackofficeContactsContactIdRoute,
  BackofficeContactsIndexRoute: BackofficeContactsIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

interface EditorRouteChildren {
  EditorListingIdRoute: typeof EditorListingIdRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorListingIdRoute: EditorListingIdRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

interface EmailRouteChildren {
  EmailEmailIdRoute: typeof EmailEmailIdRoute
  EmailIndexRoute: typeof EmailIndexRoute
}

const EmailRouteChildren: EmailRouteChildren = {
  EmailEmailIdRoute: EmailEmailIdRoute,
  EmailIndexRoute: EmailIndexRoute,
}

const EmailRouteWithChildren = EmailRoute._addFileChildren(EmailRouteChildren)

interface ListingsListingIdRouteChildren {
  ListingsListingIdActivitiesRoute: typeof ListingsListingIdActivitiesRoute
  ListingsListingIdClientReportRoute: typeof ListingsListingIdClientReportRoute
  ListingsListingIdDemographicsRoute: typeof ListingsListingIdDemographicsRoute
  ListingsListingIdDocumentsRoute: typeof ListingsListingIdDocumentsRoute
  ListingsListingIdEditRoute: typeof ListingsListingIdEditRoute
  ListingsListingIdEmailRoute: typeof ListingsListingIdEmailRoute
  ListingsListingIdFilesRoute: typeof ListingsListingIdFilesRoute
  ListingsListingIdFinancialsRoute: typeof ListingsListingIdFinancialsRoute
  ListingsListingIdGridsRoute: typeof ListingsListingIdGridsRoute
  ListingsListingIdLeadsRoute: typeof ListingsListingIdLeadsRoute
  ListingsListingIdMediaRoute: typeof ListingsListingIdMediaRoute
  ListingsListingIdOverviewRoute: typeof ListingsListingIdOverviewRoute
  ListingsListingIdTransactionRoute: typeof ListingsListingIdTransactionRoute
  ListingsListingIdWebsiteRoute: typeof ListingsListingIdWebsiteRoute
  ListingsListingIdIndexRoute: typeof ListingsListingIdIndexRoute
}

const ListingsListingIdRouteChildren: ListingsListingIdRouteChildren = {
  ListingsListingIdActivitiesRoute: ListingsListingIdActivitiesRoute,
  ListingsListingIdClientReportRoute: ListingsListingIdClientReportRoute,
  ListingsListingIdDemographicsRoute: ListingsListingIdDemographicsRoute,
  ListingsListingIdDocumentsRoute: ListingsListingIdDocumentsRoute,
  ListingsListingIdEditRoute: ListingsListingIdEditRoute,
  ListingsListingIdEmailRoute: ListingsListingIdEmailRoute,
  ListingsListingIdFilesRoute: ListingsListingIdFilesRoute,
  ListingsListingIdFinancialsRoute: ListingsListingIdFinancialsRoute,
  ListingsListingIdGridsRoute: ListingsListingIdGridsRoute,
  ListingsListingIdLeadsRoute: ListingsListingIdLeadsRoute,
  ListingsListingIdMediaRoute: ListingsListingIdMediaRoute,
  ListingsListingIdOverviewRoute: ListingsListingIdOverviewRoute,
  ListingsListingIdTransactionRoute: ListingsListingIdTransactionRoute,
  ListingsListingIdWebsiteRoute: ListingsListingIdWebsiteRoute,
  ListingsListingIdIndexRoute: ListingsListingIdIndexRoute,
}

const ListingsListingIdRouteWithChildren =
  ListingsListingIdRoute._addFileChildren(ListingsListingIdRouteChildren)

interface ListingsRouteChildren {
  ListingsListingIdRoute: typeof ListingsListingIdRouteWithChildren
  ListingsIndexRoute: typeof ListingsIndexRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsListingIdRoute: ListingsListingIdRouteWithChildren,
  ListingsIndexRoute: ListingsIndexRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface SuiteRouteChildren {
  SuiteIndexRoute: typeof SuiteIndexRoute
}

const SuiteRouteChildren: SuiteRouteChildren = {
  SuiteIndexRoute: SuiteIndexRoute,
}

const SuiteRouteWithChildren = SuiteRoute._addFileChildren(SuiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BackofficeRoute: BackofficeRouteWithChildren,
  EditorRoute: EditorRouteWithChildren,
  EmailRoute: EmailRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  LoginRoute: LoginRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SuiteRoute: SuiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
