import {
  faArrowRotateRight,
  faCalendarDays,
  faDoorOpen,
  faEnvelope,
  faListCheck,
  faPhone,
} from "@fortawesome/pro-regular-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import type { ContactTask } from "#/data/types";

/**
 * Presentation helpers for the contact detail Tasks column.
 *
 * Task types are scoped to the set the Add/Edit Task modal offers — Call, Email,
 * Meeting, To-Do, Follow-Up, Showing (plus "None" ⇒ no badge). Standalone tasks
 * carry an explicit type; deal-derived tasks have only a free-text label, so we
 * infer a type from it, mapping only into that same scoped set.
 */

export type TaskTypeKey =
  | "call"
  | "email"
  | "meeting"
  | "to-do"
  | "follow-up"
  | "showing";

/** Display label for each scoped task type. */
export const TASK_TYPE_LABELS: Record<TaskTypeKey, string> = {
  call: "Call",
  email: "Email",
  meeting: "Meeting",
  "to-do": "To-Do",
  "follow-up": "Follow-Up",
  showing: "Showing",
};

/**
 * Icon for each scoped task type. Drives the type badge on both task surfaces —
 * icon-only on the contact detail page, icon + label on the Tasks page.
 */
export const TASK_TYPE_ICONS: Record<TaskTypeKey, IconDefinition> = {
  call: faPhone,
  email: faEnvelope,
  meeting: faCalendarDays,
  "to-do": faListCheck,
  "follow-up": faArrowRotateRight,
  showing: faDoorOpen,
};

/** Keyword → type rules, checked in order; first match wins. */
const TYPE_RULES: Array<{ type: TaskTypeKey; keywords: string[] }> = [
  {
    type: "follow-up",
    keywords: ["follow up", "follow-up", "check in", "check-in", "circle back", "touch base"],
  },
  {
    type: "showing",
    keywords: ["tour", "showing", "walkthrough", "walk-through", "open house", "inspection", "site visit"],
  },
  { type: "call", keywords: ["call", "phone", "dial", "reach out"] },
  { type: "email", keywords: ["email", "outreach", "send"] },
  { type: "meeting", keywords: ["meeting", "meet with", "schedule", "sync"] },
  {
    type: "to-do",
    keywords: [
      "upload", "order", "publish", "review", "confirm", "prepare", "draft",
      "underwrit", "sign", "agreement", "disclosure", "title", "escrow",
      "signage", "statement", "photography", "proposal", "opinion", "diligence",
      "offer", "financing", "appraisal", "closing", "list", "archive", "task",
    ],
  },
];

/** Infers a scoped task type from a label; returns null when nothing matches. */
export function deriveTaskType(label: string): TaskTypeKey | null {
  const text = label.toLowerCase();
  for (const rule of TYPE_RULES) {
    if (rule.keywords.some((k) => text.includes(k))) return rule.type;
  }
  return null;
}

/**
 * The type key for a task, scoped to the Task types. Prefers a standalone
 * task's explicit `type`; otherwise infers from the label. Returns null when
 * there's no meaningful type (so the badge is hidden), e.g. a "None"-typed task
 * or an unmatched label.
 */
export function taskTypeKey(task: ContactTask): TaskTypeKey | null {
  if (task.type) {
    const key = task.type as TaskTypeKey;
    return TASK_TYPE_LABELS[key] ? key : null;
  }
  return deriveTaskType(task.label);
}

/**
 * Whether a task reads as AI-suggested — shown with a sparkle badge. Auto-
 * generated tasks always qualify; otherwise we surface follow-up-style tasks
 * (calls/emails/follow-ups) the assistant would queue after an interaction.
 */
export function isAiSuggested(task: ContactTask): boolean {
  if (task.autoGenerated) return true;
  const type = task.type ?? deriveTaskType(task.label);
  return type === "call" || type === "email" || type === "follow-up";
}

/**
 * Short due-date label, e.g. "July 28". Null date → null. Parses the
 * `YYYY-MM-DD` seed date as local (not UTC) so the day doesn't shift back in
 * timezones west of UTC.
 */
export function taskDueLabel(date: string | null): string | null {
  if (!date) return null;
  const [y, m, d] = date.split("-").map(Number);
  const local = new Date(y, (m ?? 1) - 1, d ?? 1);
  return local.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
  });
}
