import {
  faPhone,
  faEnvelope,
  faCalendarUsers,
  faFileSignature,
  faNoteSticky,
  faListCheck,
} from "@fortawesome/pro-regular-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import type { ContactTask } from "#/data/types";

/**
 * Presentation helpers for the contact detail Tasks column.
 *
 * The data model ({@link ContactTask}) has no explicit task *type* — tasks come
 * from deal planners as free-text labels — so we infer a type from the label to
 * drive the small type badge on each card (call, email, meeting, …). This is
 * prototype presentation logic; when tasks carry a real type field, swap
 * {@link deriveTaskType} for a direct lookup.
 */

export type ContactTaskType =
  | "call"
  | "email"
  | "meeting"
  | "document"
  | "note";

/** Icon + accessible label for each task type's badge. */
export const TASK_TYPE_META: Record<
  ContactTaskType,
  { icon: IconDefinition; label: string }
> = {
  call: { icon: faPhone, label: "Call" },
  email: { icon: faEnvelope, label: "Email" },
  meeting: { icon: faCalendarUsers, label: "Meeting" },
  document: { icon: faFileSignature, label: "Document" },
  note: { icon: faNoteSticky, label: "Note" },
};

/** Fallback icon for tasks that don't match a specific type. */
export const GENERIC_TASK_ICON = faListCheck;

/** Keyword → type rules, checked in order; first match wins. */
const TYPE_RULES: Array<{ type: ContactTaskType; keywords: string[] }> = [
  {
    type: "call",
    keywords: ["call", "phone", "follow up", "follow-up", "reach out"],
  },
  { type: "email", keywords: ["email", "send", "outreach"] },
  {
    type: "meeting",
    keywords: ["schedule", "tour", "inspection", "meeting", "walkthrough"],
  },
  {
    type: "document",
    keywords: [
      "upload",
      "order",
      "publish",
      "website",
      "agreement",
      "disclosure",
      "title",
      "escrow",
      "signage",
      "statement",
      "photography",
      "document",
    ],
  },
  {
    type: "note",
    keywords: ["review", "confirm", "underwrit", "opinion", "archive"],
  },
];

/** Infers a task type from its label; returns null when nothing matches. */
export function deriveTaskType(label: string): ContactTaskType | null {
  const text = label.toLowerCase();
  for (const rule of TYPE_RULES) {
    if (rule.keywords.some((k) => text.includes(k))) return rule.type;
  }
  return null;
}

/**
 * Whether a task reads as AI-suggested — shown with a sparkle badge. Auto-
 * generated tasks always qualify; otherwise we surface follow-up-style tasks
 * (calls/emails) the assistant would queue after an interaction.
 */
export function isAiSuggested(task: ContactTask): boolean {
  if (task.autoGenerated) return true;
  const type = deriveTaskType(task.label);
  return type === "call" || type === "email";
}

/**
 * Short due-date label, e.g. "July 28". Null date → null. Parses the
 * `YYYY-MM-DD` seed date as local (not UTC) so the day doesn't shift back in
 * timezones west of UTC.
 */
export function taskDueLabel(date: string | null): string | null {
  if (!date) return null;
  const [y, m, d] = date.split("-").map(Number);
  const local = new Date(y, (m ?? 1) - 1, d ?? 1);
  return local.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
  });
}
