import { describe, expect, it } from 'vitest'
import { generateTasks, generateDataset } from './seed'

const START = '2026-01-01T00:00:00.000Z'

describe('generateTasks', () => {
  it('returns the proposal setup checklist, auto-generated items complete', () => {
    const tasks = generateTasks('proposal', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Underwriting',
      'Listing proposal',
      "Broker's Opinion of Value",
      'Upload executed listing agreement',
      'Order professional photography',
      'Order property signage',
      'Publish listing to website',
    ])
    expect(tasks.slice(0, 3).every((t) => t.status === 'complete' && t.autoGenerated)).toBe(true)
    expect(tasks.slice(3).every((t) => t.status === 'open')).toBe(true)
  })

  it('returns active-stage marketing tasks', () => {
    const tasks = generateTasks('active', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Send marketing package',
      'Schedule property tours',
      'Review incoming offers',
      'Confirm due diligence dates',
    ])
  })

  it('returns an open closing checklist for under-contract', () => {
    const tasks = generateTasks('under-contract', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Schedule inspection',
      'Order title and escrow',
      'Confirm financing and appraisal',
      'Review closing disclosures',
    ])
    expect(tasks.filter((t) => t.status === 'complete')).toHaveLength(1)
  })

  it('returns the same closing checklist for closed, mostly complete plus one follow-up', () => {
    const tasks = generateTasks('closed', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Schedule inspection',
      'Order title and escrow',
      'Confirm financing and appraisal',
      'Review closing disclosures',
      'Send final commission statement',
    ])
    expect(tasks.slice(0, 4).every((t) => t.status === 'complete')).toBe(true)
    expect(tasks[4].status).toBe('open')
  })

  it('returns a light checklist for inactive', () => {
    const tasks = generateTasks('inactive', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Archive listing documents',
      'Follow up with owner',
    ])
  })

  it('offsets task dates from the given stage-start date', () => {
    const tasks = generateTasks('proposal', START)
    const upload = tasks.find((t) => t.label === 'Upload executed listing agreement')
    expect(upload?.date).toBe('2026-01-03')
  })
})

describe('property units + financial records seed', () => {
  const { properties } = generateDataset()

  it('gives every property at least one unit with a physical shell', () => {
    for (const p of properties) {
      expect(p.units.length).toBeGreaterThan(0)
      for (const u of p.units) {
        expect(u.sqft).toBeGreaterThan(0)
        expect(typeof u.label).toBe('string')
      }
    }
  })

  it('gives every property dated financial records, newest first, latest mirroring flat actuals', () => {
    for (const p of properties) {
      expect(p.financialRecords.length).toBeGreaterThan(0)
      const dates = p.financialRecords.map((r) => r.asOf)
      const sorted = [...dates].sort().reverse()
      expect(dates).toEqual(sorted) // newest-first
      const latest = p.financialRecords[0]
      expect(latest.noi).toBe(p.noi)
      expect(latest.capRate).toBe(p.capRate)
    }
  })

  it('derives occupancyPct from vacancy and gives a notes string', () => {
    for (const p of properties) {
      expect(p.occupancyPct).toBeGreaterThanOrEqual(0)
      expect(p.occupancyPct).toBeLessThanOrEqual(100)
      expect(typeof p.notes).toBe('string')
    }
  })

  it('makes each financial record internally consistent (NOI = EGI − OpEx, occupancy = 1 − vacancy)', () => {
    for (const p of properties) {
      for (const r of p.financialRecords) {
        expect(r.noi).toBe(r.effectiveGrossIncome - r.operatingExpenses)
        expect(Math.abs(r.occupancyPct - (1 - r.vacancyRate) * 100)).toBeLessThan(0.1)
      }
    }
  })

  it('varies figures year-to-year (history is not the same numbers copied down)', () => {
    // Income trends down into the past, so NOI is distinct per year for every
    // income-producing property. Land / zero-NOI assets stay flat at 0 — skip those.
    let checked = 0
    for (const p of properties) {
      if (p.noi <= 0) continue
      checked++
      expect(new Set(p.financialRecords.map((r) => r.noi)).size).toBeGreaterThan(1)
    }
    expect(checked).toBeGreaterThan(0) // guard against a vacuous pass
    // Vacancy drifts across years too (dataset-level, robust against a clamped edge case).
    expect(
      properties.some((p) => new Set(p.financialRecords.map((r) => r.vacancyRate)).size > 1),
    ).toBe(true)
  })
})

describe('unit sale history seed', () => {
  const { properties } = generateDataset()

  it('is newest-first with positive prices, consistent $/SF, and plausible cap rates', () => {
    let sawSome = false
    for (const p of properties) {
      for (const u of p.units) {
        expect(Array.isArray(u.saleHistory)).toBe(true)
        if (u.saleHistory.length > 0) sawSome = true
        const dates = u.saleHistory.map((s) => s.date)
        expect(dates).toEqual([...dates].sort().reverse()) // newest first
        for (const s of u.saleHistory) {
          expect(s.price).toBeGreaterThan(0)
          expect(s.capRateAtSale).toBeGreaterThan(0)
          expect(s.capRateAtSale).toBeLessThan(0.15)
          if (u.sqft > 0) expect(Math.abs(s.pricePerSf - s.price / u.sqft)).toBeLessThan(1)
        }
      }
    }
    expect(sawSome).toBe(true) // at least some units carry a sale history
  })
})
