import { describe, expect, it } from 'vitest'
import { generateTasks, generateDataset } from './seed'
import { findTeammate } from './teammates'
import type { ListingStage } from './types'
import { buildContactTimeline } from '#/components/contacts/timelineArcs'
import { matchesContactFilters, emptyContactFilters } from '#/components/contacts/contactFilterModel'
import {
  TASK_TYPE_LABELS,
  deriveTaskType,
  type TaskTypeKey,
} from '#/components/contacts/taskDisplay'

const START = '2026-01-01T00:00:00.000Z'

describe('generateTasks', () => {
  it('returns the proposal setup checklist, auto-generated items complete', () => {
    const tasks = generateTasks('proposal', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Underwriting',
      'Listing proposal',
      "Broker's Opinion of Value",
      'Call owner to confirm pricing strategy',
      'Upload executed listing agreement',
      'Order professional photography',
      'Order property signage',
      'Publish listing to website',
    ])
    expect(tasks.slice(0, 3).every((t) => t.status === 'complete' && t.autoGenerated)).toBe(true)
    expect(tasks.slice(3).every((t) => t.status === 'open')).toBe(true)
  })

  it('returns active-stage marketing tasks', () => {
    const tasks = generateTasks('active', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Send marketing package',
      'Email updated marketing package to prospects',
      'Schedule property tours',
      'Review incoming offers',
      'Confirm due diligence dates',
    ])
  })

  it('returns the contract-to-close checklist for under-contract, all open', () => {
    const tasks = generateTasks('under-contract', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Execute purchase agreement (PSA)',
      'Collect earnest money',
      'Meeting with title company on closing logistics',
      'Complete due diligence',
      'Finalize buyer financing',
      'Clear closing contingencies',
      'Prepare closing documents',
      'Set agreed closing date',
    ])
    expect(tasks.filter((t) => t.status === 'complete')).toHaveLength(0)
  })

  it('returns the brokerage back-office checklist for closed', () => {
    const tasks = generateTasks('closed', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Review voucher',
      'Set up pre-split deductions',
    ])
    expect(tasks.every((t) => t.status === 'open')).toBe(true)
  })

  it('returns a light checklist for inactive', () => {
    const tasks = generateTasks('inactive', START)
    expect(tasks.map((t) => t.label)).toEqual([
      'Archive listing documents',
      'Follow up with owner',
    ])
  })

  it('offsets task dates from the given stage-start date', () => {
    const tasks = generateTasks('proposal', START)
    const upload = tasks.find((t) => t.label === 'Upload executed listing agreement')
    expect(upload?.date).toBe('2026-01-03')
  })

  // The sparkle badge means "the assistant queued this", which is a different
  // thing from `autoGenerated` ("the system produced this deliverable", which
  // earns a Review button in the planner). Conflating them put a sparkle on
  // every completed underwrite and BOV.
  it('marks only assistant-queued tasks createdByAi, never system deliverables', () => {
    const stages: ListingStage[] = ['proposal', 'active', 'under-contract', 'closed', 'inactive']
    const all = stages.flatMap((s) => generateTasks(s, START))

    expect(all.filter((t) => t.createdByAi).map((t) => t.label)).toEqual([
      'Call owner to confirm pricing strategy',
      'Follow up with owner',
    ])
    // The system deliverables stay unflagged, however many of them complete.
    expect(all.filter((t) => t.autoGenerated).some((t) => t.createdByAi)).toBe(false)
  })

  // The Tasks page badges a task by the type derived from its label, so the
  // stage plans have to be worded such that every type is actually reachable —
  // otherwise the page only ever shows To-Do. Open tasks only: a type that
  // exists solely on completed work is invisible by default.
  it('covers every task type across the stage plans, in open work', () => {
    const stages: ListingStage[] = ['proposal', 'active', 'under-contract', 'closed', 'inactive']
    const openTypes = new Set(
      stages
        .flatMap((s) => generateTasks(s, START))
        .filter((t) => t.status !== 'complete')
        .map((t) => deriveTaskType(t.label)),
    )
    for (const type of Object.keys(TASK_TYPE_LABELS) as TaskTypeKey[]) {
      expect(openTypes, `no open seeded task derives the "${type}" type`).toContain(type)
    }
  })
})

describe('property stage seed', () => {
  const { properties, listings } = generateDataset()
  const dealPropertyIds = new Set(listings.map((l) => l.propertyId))

  it('gives a property a stage only when a deal sits on it', () => {
    for (const p of properties) {
      if (dealPropertyIds.has(p.id)) expect(p.status).not.toBeNull()
      // No deal means no stage — not `inactive`, which means a deal was lost.
      else expect(p.status).toBeNull()
    }
  })

  it('seeds a meaningful population of properties with no deal at all', () => {
    const noDeal = properties.filter((p) => p.status === null)
    expect(noDeal.length).toBeGreaterThanOrEqual(8)
    // And they must be ordinary records, not degenerate ones.
    for (const p of noDeal) expect(p.buildingSqFt).toBeGreaterThan(0)
  })

  it("matches each deal-bearing property's stage to a deal on it", () => {
    for (const l of listings) {
      const p = properties.find((x) => x.id === l.propertyId)
      expect(p?.status).not.toBeNull()
    }
  })
})

describe('property units + financial records seed', () => {
  const { properties } = generateDataset()

  it('gives every property at least one unit with a physical shell', () => {
    for (const p of properties) {
      expect(p.units.length).toBeGreaterThan(0)
      for (const u of p.units) {
        expect(u.sqft).toBeGreaterThan(0)
        expect(typeof u.label).toBe('string')
      }
    }
  })

  it('gives every property dated financial records, newest first, latest mirroring flat actuals', () => {
    for (const p of properties) {
      expect(p.financialRecords.length).toBeGreaterThan(0)
      const dates = p.financialRecords.map((r) => r.asOf)
      const sorted = [...dates].sort().reverse()
      expect(dates).toEqual(sorted) // newest-first
      const latest = p.financialRecords[0]
      expect(latest.noi).toBe(p.noi)
      expect(latest.capRate).toBe(p.capRate)
    }
  })

  it('derives occupancyPct from vacancy and gives a notes string', () => {
    for (const p of properties) {
      expect(p.occupancyPct).toBeGreaterThanOrEqual(0)
      expect(p.occupancyPct).toBeLessThanOrEqual(100)
      expect(typeof p.notes).toBe('string')
    }
  })

  it('makes each financial record internally consistent (NOI = EGI − OpEx, occupancy = 1 − vacancy)', () => {
    for (const p of properties) {
      for (const r of p.financialRecords) {
        expect(r.noi).toBe(r.effectiveGrossIncome - r.operatingExpenses)
        expect(Math.abs(r.occupancyPct - (1 - r.vacancyRate) * 100)).toBeLessThan(0.1)
      }
    }
  })

  it('varies figures year-to-year (history is not the same numbers copied down)', () => {
    // Income trends down into the past, so NOI is distinct per year for every
    // income-producing property. Land / zero-NOI assets stay flat at 0 — skip those.
    let checked = 0
    for (const p of properties) {
      if (p.noi <= 0) continue
      checked++
      expect(new Set(p.financialRecords.map((r) => r.noi)).size).toBeGreaterThan(1)
    }
    expect(checked).toBeGreaterThan(0) // guard against a vacuous pass
    // Vacancy drifts across years too (dataset-level, robust against a clamped edge case).
    expect(
      properties.some((p) => new Set(p.financialRecords.map((r) => r.vacancyRate)).size > 1),
    ).toBe(true)
  })
})

describe('unit sale history seed', () => {
  const { properties } = generateDataset()

  it('is newest-first with positive prices, consistent $/SF, and plausible cap rates', () => {
    let sawSome = false
    for (const p of properties) {
      for (const u of p.units) {
        expect(Array.isArray(u.saleHistory)).toBe(true)
        if (u.saleHistory.length > 0) sawSome = true
        const dates = u.saleHistory.map((s) => s.date)
        expect(dates).toEqual([...dates].sort().reverse()) // newest first
        for (const s of u.saleHistory) {
          expect(s.price).toBeGreaterThan(0)
          expect(s.capRateAtSale).toBeGreaterThan(0)
          expect(s.capRateAtSale).toBeLessThan(0.15)
          if (u.sqft > 0) expect(Math.abs(s.pricePerSf - s.price / u.sqft)).toBeLessThan(1)
        }
      }
    }
    expect(sawSome).toBe(true) // at least some units carry a sale history
  })
})

describe('lastActivityAt', () => {
  it("matches each hero's newest timeline beat, so the Last Activity filter is true", () => {
    // The fixtures pin lastActivityDaysAgo by hand (the arcs are hand-authored),
    // so this walks the real timeline and fails loudly if the two ever drift.
    const { contacts } = generateDataset()
    for (const c of contacts.filter((x) => x.heroKey)) {
      const newest = buildContactTimeline(c, [])
        .map((e) => Date.parse(e.timestamp))
        .sort((a, b) => b - a)[0]
      const activityAt = Date.parse(c.lastActivityAt ?? c.lastContactedAt!)
      // Same day — the fixture is day-granular, the arc carries a time of day.
      expect(Math.abs(newest - activityAt)).toBeLessThan(36 * 60 * 60 * 1000)
    }
  })

  it("puts Rosa's inbound voicemail inside the past-7-days bucket", () => {
    const { contacts } = generateDataset()
    const rosa = contacts.find((c) => c.heroKey === 'rosa')!
    // We last spoke 8 days ago — outside the bucket…
    const contactedAge = Date.now() - Date.parse(rosa.lastContactedAt!)
    expect(contactedAge).toBeGreaterThan(7 * 86_400_000)
    // …but her voicemail yesterday is what the filter reads.
    expect(matchesContactFilters(rosa, { ...emptyContactFilters(), lastActivity: '7d' })).toBe(true)
  })
})

describe('voucher approval seed', () => {
  const { listings } = generateDataset()

  it('gives every Approved voucher an approval, and no other voucher one', () => {
    // The whole reason `approval` is one nested object rather than two flat
    // nullable fields: the pair is all-or-nothing, and this is what says so.
    for (const l of listings) {
      const voucher = l.transaction.backOffice
      if (voucher.status === 'Approved') expect(voucher.approval).not.toBeNull()
      else expect(voucher.approval).toBeNull()
    }
  })

  it('names a reviewer who is actually on the roster', () => {
    const approved = listings
      .map((l) => l.transaction.backOffice)
      .filter((v) => v.approval !== null)
    expect(approved.length).toBeGreaterThan(0)
    for (const v of approved) {
      expect(findTeammate(v.approval!.reviewerId)).toBeDefined()
    }
  })

  it('never signs a voucher off before the deal closed', () => {
    for (const l of listings) {
      const voucher = l.transaction.backOffice
      if (!voucher.approval || !voucher.closeDate) continue
      expect(voucher.approval.approvedOn >= voucher.closeDate).toBe(true)
    }
  })
})

describe('voucher payers seed', () => {
  const { listings, contacts } = generateDataset()
  const contactIds = new Set(contacts.map((c) => c.id))

  it('points every receivable at a contact that exists', () => {
    for (const deal of listings) {
      for (const r of deal.transaction.backOffice.receivables) {
        expect(contactIds.has(r.payerContactId)).toBe(true)
      }
    }
  })

  it("lists every receivable's payer among the voucher's payers", () => {
    // The rule the Payers section depends on: a receivable cannot bill someone
    // the voucher has not named as a payer.
    for (const deal of listings) {
      const back = deal.transaction.backOffice
      for (const r of back.receivables) {
        expect(back.payerContactIds).toContain(r.payerContactId)
      }
    }
  })

  it('has no duplicate payers on a voucher', () => {
    for (const deal of listings) {
      const ids = deal.transaction.backOffice.payerContactIds
      expect(new Set(ids).size).toBe(ids.length)
    }
  })
})
